global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-render'
    metrics_path: '/api/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['titantrack-wgv3.onrender.com']